export const list = [
  "Postmodernism",
  "Homebrewing",
  "Ursula K. Le Guin",
  "Historical materialism",
  "Yacht rock",
  "The Tao Te Ching",
  "Capitalist realism",
  "Ernst Bloch",
  "Improving this site",
  "Fredric Jameson",
  "The Weimar Republic",
  "Root (board game)",
  "The Shakespeare Authorship Question",
  "The German Peasants’ War",
  "Acid communism",
  "Andrei Tarkovsky",
  "The Sonoma Coast",
  "Puncuated equilibrium",
  "Liberation theology",
  "Biblical source criticism",
  "Typography",
  "Mechanical keyboards",
  "Learning a new programming language",
  "The Golden Ratio",
];
