name: Publish on Deno Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AIRTABLE_ACCESS_TOKEN: ${{ secrets.AIRTABLE_ACCESS_TOKEN }}
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      FATHOM_ACCESS_TOKEN: ${{ secrets.FATHOM_ACCESS_TOKEN }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46

      - name: Build site
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: cheap-tuna-20
          entrypoint: server/serve.ts
